### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by pradyunsg** [borntyping/v#1]
Hi @borntyping!

I had started writing a similar tool for myself and realised that you have this name on PyPI, for building a tool very similar to the one I have in my head.

You can see a really early-draft of my thought process: https://github.com/pradyunsg/dotfiles/blob/master/src/python/virtualenvwrapper.zsh

Would you be willing to collaborate on this?

**Comment by borntyping** [comment]
Sure!

I don't really use or maintain `v` at the moment (mostly using [Pipenv](https://github.com/pypa/pipenv) instead), and I'm not aware of any other users - I'd be more than happy to free up the name on PyPi so another project can use it.

**Comment by pradyunsg** [comment]
Oh. Okay. In that case, would you be willing add `pradyunsg` as an Owner for `v` on PyPI?

**Comment by borntyping** [comment]
@pradyunsg I've removed the `v` project instead - it should be possible to create a new one with that name now.

(I'm still interested in watching and helping with this if I can, but I'm trying to cut down on the number of projects I'm at all responsible for at the moment - I've far too many half finished or unmaintained codebases!)

**Comment by pradyunsg** [comment]
Awesome! Thank you!

I've gone ahead and published a 0.0.0 version of the same package to get ownership of the name. I'll ping you here when I make the GitHub repo for the project. :)

**Comment by borntyping** [comment]
😄
